pipelines:
  yamlpipe1:
    group: simple
    materials:
      mygit:
        type: configrepo
    stages:
      - build: # name of stage
          jobs:
            build: # name of the job
              environment_variables:
                ENV_PASSWORD: secret
              tasks:
               - exec: # indicates type of task
                   command: bash
                   arguments:
                     - -c
                     - "echo $ENV_PASSWORD"
